import type { EcosystemData } from '@/types/ecosystem';

export const createFallbackEcosystemData = (
    t: (key: string) => string
): EcosystemData => ({
    core: {
        label: 'HUB-EGI',
        tagline: t('fallback.core.tagline'),
        cat: t('fallback.core.cat'),
        color: 0xFFD700,
        desc: t('fallback.core.desc'),
        bullets: [
            t('fallback.core.bullet1'),
            t('fallback.core.bullet2'),
            t('fallback.core.bullet3'),
        ],
        egi_link: t('fallback.core.link'),
        route: '/hub',
    },
    project: {
        label: t('fallback.project.label'),
        tagline: t('fallback.project.tagline'),
        cat: t('fallback.project.cat'),
        color: 0x00FFAA,
        desc: t('fallback.project.desc'),
        bullets: [
            t('fallback.project.bullet1'),
            t('fallback.project.bullet2'),
            t('fallback.project.bullet3'),
        ],
        egi_link: t('fallback.project.link'),
        route: '/projects',
    },
    policy: {
        label: t('fallback.policy.label'),
        tagline: t('fallback.policy.tagline'),
        cat: t('fallback.policy.cat'),
        color: 0x4B0082,
        desc: t('fallback.policy.desc'),
        bullets: [
            t('fallback.policy.bullet1'),
            t('fallback.policy.bullet2'),
            t('fallback.policy.bullet3'),
        ],
        egi_link: t('fallback.policy.link'),
        route: '/policy',
    },
    tech: {
        label: t('fallback.tech.label'),
        tagline: t('fallback.tech.tagline'),
        cat: t('fallback.tech.cat'),
        color: 0x50C878,
        desc: t('fallback.tech.desc'),
        bullets: [
            t('fallback.tech.bullet1'),
            t('fallback.tech.bullet2'),
            t('fallback.tech.bullet3'),
        ],
        egi_link: t('fallback.tech.link'),
        route: '/tech',
    },
    payments: {
        label: t('fallback.payments.label'),
        tagline: t('fallback.payments.tagline'),
        cat: t('fallback.payments.cat'),
        color: 0xF4C430,
        desc: t('fallback.payments.desc'),
        bullets: [
            t('fallback.payments.bullet1'),
            t('fallback.payments.bullet2'),
            t('fallback.payments.bullet3'),
        ],
        egi_link: t('fallback.payments.link'),
        route: '/payments',
    },
    info: {
        label: t('fallback.info.label'),
        tagline: t('fallback.info.tagline'),
        cat: t('fallback.info.cat'),
        color: 0x00BFFF,
        desc: t('fallback.info.desc'),
        bullets: [
            t('fallback.info.bullet1'),
            t('fallback.info.bullet2'),
            t('fallback.info.bullet3'),
        ],
        egi_link: t('fallback.info.link'),
        route: '/info',
    },
    oracode: {
        label: t('fallback.oracode.label'),
        tagline: t('fallback.oracode.tagline'),
        cat: t('fallback.oracode.cat'),
        color: 0xE34234,
        desc: t('fallback.oracode.desc'),
        bullets: [
            t('fallback.oracode.bullet1'),
            t('fallback.oracode.bullet2'),
            t('fallback.oracode.bullet3'),
        ],
        egi_link: t('fallback.oracode.link'),
        route: '/oracode',
    },
    epp: {
        label: t('fallback.epp.label'),
        tagline: t('fallback.epp.tagline'),
        cat: t('fallback.epp.cat'),
        color: 0x228B22,
        desc: t('fallback.epp.desc'),
        bullets: [
            t('fallback.epp.bullet1'),
            t('fallback.epp.bullet2'),
            t('fallback.epp.bullet3'),
        ],
        egi_link: t('fallback.epp.link'),
        route: '/ambiente',
    },
    orbitalConfig: [
        { id: 'project', orbit: 1 },
        { id: 'policy', orbit: 1 },
        { id: 'tech', orbit: 1 },
        { id: 'payments', orbit: 2 },
        { id: 'info', orbit: 2 },
        { id: 'epp', orbit: 2 },
        { id: 'oracode', orbit: 3 },
    ],
});
